spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # Route to Auth Service
        - id: auth-service
          uri: http://localhost:4001
          predicates:
            - Path=/api/auth/**

        # Route to CMS Service
        - id: cms-service
          uri: http://localhost:8082
          predicates:
            - Path=/cms/**

        # Example of a secured service (requires valid JWT)
        - id: admin-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/admin/**
          filters:
            - RewritePath=/api/admin/(?<remaining>.*), /$\\{remaining}  # Optional: Rewrite path to downstream
            - RemoveRequestHeader=Cookie  # Optional: Remove unnecessary headers like cookies

server:
  port: 4000

# Security settings (Optional for reference)
security:
  enabled: true
  jwt:
    secret: your-secret-key  # Replace with your actual secret
    expiration: 3600         # Token expiration duration