spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # Route to Auth Service
        - id: auth-service
          uri: http://localhost:4001
          predicates:
            - Path=/api/auth/**

server:
  port: 4000

# Security settings (Optional for reference)
security:
  enabled: true
  jwt:
    secret: your-very-secure-64-character-or-longer-secret-key-keep-this-safe
    expiration: 3600         # Token expiration duration
