server:
  port: 4002
spring:
  application:
    name: department-service
eureka:

  client:
    service-url:
      defaultZone: http://admin:admin123@localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1


    server:
      port: 4001
    spring:
      application:
        name: cms-services

    eureka:

      client:
        service-url:
          defaultZone: http://admin:admin123@localhost:8761/eureka/
        fetch-registry: true
        register-with-eureka: true
      instance:
        prefer-ip-address: true
        ip-address: 127.0.0.1