server:
  port: 4004
spring:
  application:
    name: finance-service

eureka:
  client:
    service-url:
     defaultZone: http://admin:admin123@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
